### ISSUE TITLE
Camera and GPIO error after a while

### ISSUE THREAD

**Issue by Tinker232** [reuterbal/photobooth#196]
Hey,
I use the modified version from @websta911 with fancy layouts etc. with my raspberrypi4 and a canon selphy1300 (connected via wifi).
The photobooth works fine, but when the photobooth is not used for approximately 30/40 minutes and someone hits the button, there is no live picture from the camera and short time later an error occurs. (Camera and GPIO)

**Screenshots/Screencast**

<a href="https://www.bilder-upload.eu/bild-b01312-1571784171.png.html" target="_blank"><img src="https://www.bilder-upload.eu/thumb/b01312-1571784171.png" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

**Hardware (please complete the following information)**

 - Raspberry PI4 
 - Camera 70D
 - Canon Selphy CP1300
 - GPIO: [No]

**Photobooth log**

```
2019-10-15 21:16:51,997 - root - INFO - Initializing photobooth
2019-10-15 21:16:51,997 - root - INFO - Photobooth version: 0.5.dev6+g871b526
2019-10-15 21:16:51,998 - root - INFO - Reading config file "/home/pi/photobooth/photobooth/defaults.cfg"
2019-10-15 21:16:52,001 - root - INFO - Reading config file "photobooth.cfg"
2019-10-15 21:16:52,051 - root - INFO - GPIO disabled
2019-10-15 21:16:52,069 - root - INFO - Number of last existing file: 35
2019-10-15 21:16:52,074 - root - INFO - Saving pictures as "2019-10-15/photoboothXXXXX.jpg"
2019-10-15 21:16:52,081 - root - INFO - Number of last existing file: 0
2019-10-15 21:16:52,083 - root - INFO - Saving pictures as "2019-10-15/src/photobooth_shot_XXXXX.jpg"
2019-10-15 21:16:52,087 - root - INFO - fancy "False"
2019-10-15 21:16:52,843 - root - INFO - Using printer "Canon_SELPHY_CP1300"
2019-10-15 21:16:54,117 - root - INFO - Using python-gphoto2 bindings
2019-10-15 21:16:54,403 - root - INFO - Camera summary: Manufacturer: Canon Inc.
Model: Canon EOS 70D
  Version: 3-1.1.1
  Serial Number: f1266c86fd7c41cf848c8b4d6f39d057
Vendor Extension ID: 0xb (1.0)

Capture Formats: JPEG
Display Formats: Association/Directory, Script, DPOF, MS AVI, MS Wave, JPEG, CRW, Unknown(b103), Unknown(bf02), Defined Type, Unknown(b104), Unknown(b105)

Device Capabilities:
	File Download, File Deletion, File Upload
	No Image Capture, No Open Capture, Canon EOS Capture, Canon EOS Capture 2
	Canon Wifi support

Storage Devices Summary:
store_00020001:
	StorageDescription: SD
	VolumeLabel: None
	Storage Type: Removable RAM (memory card)
	Filesystemtype: Digital Camera Layout (DCIM)
	Access Capability: Read-Write
	Maximum Capability: 31037849600 (29600 MB)
	Free Space (Bytes): 20006240256 (19079 MB)
	Free Space (Images): -1

Device Property Summary:
Model ID(0xd049):(read only) (type=0x6) 2147484453
Property 0xd402:(read only) (type=0xffff) 'Canon EOS 70D'
Property 0xd407:(read only) (type=0x6) 1
Property 0xd406:(readwrite) (type=0xffff) 'Unknown Initiator'
Property 0xd303:(read only) (type=0x2) 1
Battery Level(0x5001):(read only) (type=0x2) Enumeration [100,0,75,0,50] value: 100% (100)

2019-10-15 21:16:54,614 - root - INFO - Loading camera config "canoneos70d.cfg"
2019-10-15 21:16:54,638 - root - INFO - Camera configuration:
Camera Actions [actions]: 
    Synchronize camera date and time with PC [syncdatetimeutc]: 0
    Synchronize camera date and time with PC [syncdatetime]: 0
    UI Lock [uilock]: 2
    Drive Canon DSLR Autofocus [autofocusdrive]: 0
    Drive Canon DSLR Manual focus [manualfocusdrive]: None (Near 1, Near 2, Near 3, None, Far 1, Far 2, Far 3, )
    Cancel Canon DSLR Autofocus [cancelautofocus]: 0
    Canon EOS Zoom [eoszoom]: 0
    Canon EOS Zoom Position [eoszoomposition]: 0,0
    Canon EOS Viewfinder [viewfinder]: 2
    Canon EOS Remote Release [eosremoterelease]: None (None, Press Half, Press Full, Release Half, Release Full, Immediate, Press 1, Press 2, Press 3, Release 1, Release 2, Release 3, )
    PTP Opcode [opcode]: 0x1001,0xparam1,0xparam2
Camera Settings [settings]: 
    Camera Date and Time [datetimeutc]: 1571774696
    Camera Date and Time [datetime]: 1571774696
    Quick Review Time [reviewtime]: None (None, 2 seconds, 4 seconds, 8 seconds, Hold, )
    Camera Output [output]: PC (Off, TFT, PC, TFT + PC, Setting 4, Setting 5, Setting 6, Setting 7, Unknown value 0008, Unknown value 0009, Unknown value 000a, Unknown value 000b, )
    Recording Destination [movierecordtarget]: Unknown value 0003 (Unknown value 0003, )
    EVF Mode [evfmode]: 1 (1, 0, )
    Owner Name [ownername]: 
    Artist [artist]: 
    Copyright [copyright]: 
    Custom Functions Ex [customfuncex]: 90,1,4,84,4,706,1,0,70f,2,0,2,40a,1,3,70c,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    Focus Info [focusinfo]: eosversion=4,size=5472x3648,size2=5472x3648,points={{-1395,0,277,229},{-897,401,277,229},{-897,0,277,229},{-897,-401,277,229},{-399,401,277,229},{-399,0,277,229},{-399,-401,277,229},{0,755,277,229},{0,401,277,229},{0,0,277,229},{0,-401,277,229},{0,-755,277,229},{399,401,277,229},{399,0,277,229},{399,-401,277,229},{897,401,277,229},{897,0,277,229},{897,-401,277,229},{1395,0,277,229}},select={},unknown={ffff070000000000ffff}
    Focus Area [focusarea]: 7
    Auto Power Off [autopoweroff]: 0
    Depth of Field [depthoffield]: 0
    Capture Target [capturetarget]: Internal RAM (Internal RAM, Memory card, )
    Capture [capture]: 0
Camera Status Information [status]: 
    Serial Number [serialnumber]: f1266c86fd7c41cf848c8b4d6f39d057
    Camera Manufacturer [manufacturer]: Canon Inc.
    Camera Model [cameramodel]: Canon EOS 70D
    Device Version [deviceversion]: 3-1.1.1
    Vendor Extension [vendorextension]: None
    Camera Model [model]: 2147484453
    PTP Version [ptpversion]: 256
    Battery Level []: 100%
    Battery Level [batterylevel]: 100%
    Lens Name [lensname]: EF-S18-135mm f/3.5-5.6 IS STM
    Serial Number [eosserialnumber]: 333058000085
    Shutter Counter [shuttercounter]: 6853
    Available Shots [availableshots]: 671086
Image Settings [imgsettings]: 
    Image Format [imageformat]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    Image Format SD [imageformatsd]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    Image Format CF [imageformatcf]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    ISO Speed [iso]: Auto (Auto, )
    Color Temperature [colortemperature]: 5200
    WhiteBalance X A [whitebalancexa]: 0
    WhiteBalance X B [whitebalancexb]: 0
    Color Space [colorspace]: sRGB (sRGB, )
Capture Settings [capturesettings]: 
    Focus Mode [focusmode]: One Shot (One Shot, )
    Continuous AF [continuousaf]: Off (Off, On, )
    Aspect Ratio [aspectratio]: 3:2 (3:2, )
    Storage Device [storageid]: 00020001
    High ISO Noise Reduction [highisonr]: Off (Off, )
    Canon Auto Exposure Mode [autoexposuremode]: Unknown value 0016 (P, TV, AV, Manual, Bulb, A_DEP, DEP, Custom, Lock, Green, Night Portrait, Sports, Portrait, Landscape, Closeup, Flash Off, Unknown value 0016, )
    Drive Mode [drivemode]: Single (Single, Continuous high speed, Continuous low speed, Single silent, Continuous silent, Timer 10 sec, Timer 2 sec, )
    Aperture [aperture]: implicit auto (implicit auto, )
    Shutter Speed [shutterspeed]: auto (auto, )
    Bracket Mode [bracketmode]: 0
    Auto Exposure Bracketing [aeb]: off (off, )
Other PTP Device Properties [other]: 
    Model ID [d049]: -2147482843
    PTP Property 0xd402 [d402]: Canon EOS 70D
    PTP Property 0xd407 [d407]: 1
    PTP Property 0xd406 [d406]: Unknown Initiator
    PTP Property 0xd303 [d303]: 1
    Battery Level [5001]: 100 (100, 0, 75, 0, 50, )

2019-10-15 21:16:54,639 - root - INFO - Using camera with preview functionality
2019-10-15 21:16:56,514 - root - INFO - _skip: "[4]"
2019-10-15 21:16:56,515 - root - INFO - Adding Logo : "False"
2019-10-15 21:16:56,515 - root - INFO - Using logo "/home/pi/Bilder/1024px-logo.png"
2019-10-15 21:16:56,515 - root - INFO - Using background "/home/pi/photobooth/supplementals/backgrounds/Fotopaper_background_forever_59.jpg"
2019-10-15 21:17:21,616 - root - INFO - Pic "0"
2019-10-15 21:17:21,690 - root - INFO - Pic "1"
2019-10-15 21:17:21,758 - root - INFO - Pic "2"
2019-10-15 21:17:21,907 - root - INFO - Saving picture as 2019-10-15/photobooth00036.jpg
2019-10-15 23:12:30,440 - root - ERROR - CameraProcess: Exception "[-1] Unspecified error"
Traceback (most recent call last):
  File "/home/pi/photobooth/photobooth/main.py", line 66, in run
    if cap.run():
  File "/home/pi/photobooth/photobooth/camera/__init__.py", line 109, in run
    self.handleState(state)
  File "/home/pi/photobooth/photobooth/camera/__init__.py", line 120, in handleState
    self.capturePreview()
  File "/home/pi/photobooth/photobooth/camera/__init__.py", line 146, in capturePreview
    picture = self._cap.getPreview()
  File "/home/pi/photobooth/photobooth/camera/CameraGphoto2.py", line 134, in getPreview
    camera_file = self._cap.capture_preview()
gphoto2.GPhoto2Error: [-1] Unspecified error
2019-10-15 23:12:30,459 - root - ERROR - Camera: [-1] Unspecified error
2019-10-15 23:12:31,000 - root - ERROR - Main: Exception "Unknown Event type "capture""
Traceback (most recent call last):
  File "/home/pi/photobooth/photobooth/main.py", line 164, in mainloop
    exit_code = context.handleEvent(event)
  File "/home/pi/photobooth/photobooth/StateMachine.py", line 84, in handleEvent
    self.state.handleEvent(event, self)
  File "/home/pi/photobooth/photobooth/StateMachine.py", line 289, in handleEvent
    raise TypeError('Unknown Event type "{}"'.format(event))
TypeError: Unknown Event type "capture"
2019-10-15 23:12:31,009 - root - ERROR - Gpio: Unknown Event type "capture"
2019-10-15 23:13:43,560 - root - ERROR - Main: Exception "Unknown Event type "abort""
Traceback (most recent call last):
  File "/home/pi/photobooth/photobooth/main.py", line 164, in mainloop
    exit_code = context.handleEvent(event)
  File "/home/pi/photobooth/photobooth/StateMachine.py", line 84, in handleEvent
    self.state.handleEvent(event, self)
  File "/home/pi/photobooth/photobooth/StateMachine.py", line 359, in handleEvent
    raise TypeError('Unknown Event type "{}"'.format(event))
TypeError: Unknown Event type "abort"
2019-10-15 23:13:43,579 - root - ERROR - Gpio: Unknown Event type "abort"
2019-10-15 23:14:30,861 - root - INFO - Writing config file "photobooth.cfg"
2019-10-15 23:14:30,921 - root - INFO - Restarting photobooth and reloading config
2019-10-15 23:14:30,924 - root - INFO - Photobooth version: 0.5.dev6+g871b526
2019-10-15 23:14:30,926 - root - INFO - Reading config file "/home/pi/photobooth/photobooth/defaults.cfg"
2019-10-15 23:14:30,934 - root - INFO - Reading config file "photobooth.cfg"
2019-10-15 23:14:31,012 - root - INFO - Number of last existing file: 36
2019-10-15 23:14:31,015 - root - INFO - Saving pictures as "2019-10-15/photoboothXXXXX.jpg"
2019-10-15 23:14:31,017 - root - INFO - Number of last existing file: 0
2019-10-15 23:14:31,018 - root - INFO - Saving pictures as "2019-10-15/src/photobooth_shot_XXXXX.jpg"
2019-10-15 23:14:31,019 - root - INFO - GPIO disabled
2019-10-15 23:14:31,047 - root - INFO - fancy "False"
2019-10-15 23:14:31,773 - root - INFO - Using printer "Canon_SELPHY_CP1300"
2019-10-15 23:14:33,633 - root - INFO - Using python-gphoto2 bindings
2019-10-15 23:14:33,894 - root - INFO - Camera summary: Manufacturer: Canon Inc.
Model: Canon EOS 70D
  Version: 3-1.1.1
  Serial Number: f1266c86fd7c41cf848c8b4d6f39d057
Vendor Extension ID: 0xb (1.0)

Capture Formats: JPEG
Display Formats: Association/Directory, Script, DPOF, MS AVI, MS Wave, JPEG, CRW, Unknown(b103), Unknown(bf02), Defined Type, Unknown(b104), Unknown(b105)

Device Capabilities:
	File Download, File Deletion, File Upload
	No Image Capture, No Open Capture, Canon EOS Capture, Canon EOS Capture 2
	Canon Wifi support

Storage Devices Summary:
store_00020001:
	StorageDescription: SD
	VolumeLabel: None
	Storage Type: Removable RAM (memory card)
	Filesystemtype: Digital Camera Layout (DCIM)
	Access Capability: Read-Write
	Maximum Capability: 31037849600 (29600 MB)
	Free Space (Bytes): 20006240256 (19079 MB)
	Free Space (Images): -1

Device Property Summary:
Model ID(0xd049):(read only) (type=0x6) 2147484453
Property 0xd402:(read only) (type=0xffff) 'Canon EOS 70D'
Property 0xd407:(read only) (type=0x6) 1
Property 0xd406:(readwrite) (type=0xffff) 'Unknown Initiator'
Property 0xd303:(read only) (type=0x2) 1
Battery Level(0x5001):(read only) (type=0x2) Enumeration [100,0,75,0,50] value: 100% (100)

2019-10-15 23:14:34,027 - root - INFO - Loading camera config "canoneos70d.cfg"
2019-10-15 23:14:34,033 - root - INFO - Camera configuration:
Camera Actions [actions]: 
    Synchronize camera date and time with PC [syncdatetimeutc]: 0
    Synchronize camera date and time with PC [syncdatetime]: 0
    UI Lock [uilock]: 2
    Drive Canon DSLR Autofocus [autofocusdrive]: 0
    Drive Canon DSLR Manual focus [manualfocusdrive]: None (Near 1, Near 2, Near 3, None, Far 1, Far 2, Far 3, )
    Cancel Canon DSLR Autofocus [cancelautofocus]: 0
    Canon EOS Zoom [eoszoom]: 0
    Canon EOS Zoom Position [eoszoomposition]: 0,0
    Canon EOS Viewfinder [viewfinder]: 2
    Canon EOS Remote Release [eosremoterelease]: None (None, Press Half, Press Full, Release Half, Release Full, Immediate, Press 1, Press 2, Press 3, Release 1, Release 2, Release 3, )
    PTP Opcode [opcode]: 0x1001,0xparam1,0xparam2
Camera Settings [settings]: 
    Camera Date and Time [datetimeutc]: 1571781755
    Camera Date and Time [datetime]: 1571781755
    Quick Review Time [reviewtime]: None (None, 2 seconds, 4 seconds, 8 seconds, Hold, )
    Camera Output [output]: Off (Off, TFT, PC, TFT + PC, Setting 4, Setting 5, Setting 6, Setting 7, Unknown value 0008, Unknown value 0009, Unknown value 000a, Unknown value 000b, )
    Recording Destination [movierecordtarget]: None (None, )
    EVF Mode [evfmode]: 1 (1, 0, )
    Owner Name [ownername]: 
    Artist [artist]: 
    Copyright [copyright]: 
    Custom Functions Ex [customfuncex]: 90,1,4,84,4,706,1,0,70f,2,0,2,40a,1,3,70c,13,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    Focus Info [focusinfo]: eosversion=4,size=5472x3648,size2=5472x3648,points={{-1395,0,277,229},{-897,401,277,229},{-897,0,277,229},{-897,-401,277,229},{-399,401,277,229},{-399,0,277,229},{-399,-401,277,229},{0,755,277,229},{0,401,277,229},{0,0,277,229},{0,-401,277,229},{0,-755,277,229},{399,401,277,229},{399,0,277,229},{399,-401,277,229},{897,401,277,229},{897,0,277,229},{897,-401,277,229},{1395,0,277,229}},select={},unknown={ffff070000000000ffff}
    Focus Area [focusarea]: 7
    Auto Power Off [autopoweroff]: 0
    Depth of Field [depthoffield]: 0
    Capture Target [capturetarget]: Internal RAM (Internal RAM, Memory card, )
    Capture [capture]: 0
Camera Status Information [status]: 
    Serial Number [serialnumber]: f1266c86fd7c41cf848c8b4d6f39d057
    Camera Manufacturer [manufacturer]: Canon Inc.
    Camera Model [cameramodel]: Canon EOS 70D
    Device Version [deviceversion]: 3-1.1.1
    Vendor Extension [vendorextension]: None
    Camera Model [model]: 2147484453
    PTP Version [ptpversion]: 256
    Battery Level []: 100%
    Battery Level [batterylevel]: 100%
    Lens Name [lensname]: EF-S18-135mm f/3.5-5.6 IS STM
    Serial Number [eosserialnumber]: 333058000085
    Shutter Counter [shuttercounter]: 6853
    Available Shots [availableshots]: 671086
Image Settings [imgsettings]: 
    Image Format [imageformat]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    Image Format SD [imageformatsd]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    Image Format CF [imageformatcf]: Smaller JPEG (Large Fine JPEG, Large Normal JPEG, Medium Fine JPEG, Medium Normal JPEG, Small Fine JPEG, Small Normal JPEG, Smaller JPEG, Tiny JPEG, RAW + Large Fine JPEG, RAW + Large Normal JPEG, RAW + Medium Fine JPEG, RAW + Medium Normal JPEG, RAW + Small Fine JPEG, RAW + Small Normal JPEG, RAW + Smaller JPEG, RAW + Tiny JPEG, mRAW + Large Fine JPEG, mRAW + Large Normal JPEG, mRAW + Medium Fine JPEG, mRAW + Medium Normal JPEG, mRAW + Small Fine JPEG, mRAW + Small Normal JPEG, mRAW + Smaller JPEG, mRAW + Tiny JPEG, sRAW + Large Fine JPEG, sRAW + Large Normal JPEG, sRAW + Medium Fine JPEG, sRAW + Medium Normal JPEG, sRAW + Small Fine JPEG, sRAW + Small Normal JPEG, sRAW + Smaller JPEG, sRAW + Tiny JPEG, RAW, mRAW, sRAW, )
    ISO Speed [iso]: Auto (Auto, )
    Color Temperature [colortemperature]: 5200
    WhiteBalance X A [whitebalancexa]: 0
    WhiteBalance X B [whitebalancexb]: 0
    Color Space [colorspace]: sRGB (sRGB, )
Capture Settings [capturesettings]: 
    Focus Mode [focusmode]: AI Focus (AI Focus, )
    Continuous AF [continuousaf]: Off (Off, On, )
    Aspect Ratio [aspectratio]: 3:2 (3:2, )
    Storage Device [storageid]: 00020001
    High ISO Noise Reduction [highisonr]: Off (Off, )
    Canon Auto Exposure Mode [autoexposuremode]: Unknown value 0016 (P, TV, AV, Manual, Bulb, A_DEP, DEP, Custom, Lock, Green, Night Portrait, Sports, Portrait, Landscape, Closeup, Flash Off, Unknown value 0016, )
    Drive Mode [drivemode]: Single (Single, Continuous high speed, Continuous low speed, Single silent, Continuous silent, Timer 10 sec, Timer 2 sec, )
    Aperture [aperture]: implicit auto (implicit auto, )
    Shutter Speed [shutterspeed]: auto (auto, )
    Bracket Mode [bracketmode]: 0
    Auto Exposure Bracketing [aeb]: off (off, )
Other PTP Device Properties [other]: 
    Model ID [d049]: -2147482843
    PTP Property 0xd402 [d402]: Canon EOS 70D
    PTP Property 0xd407 [d407]: 1
    PTP Property 0xd406 [d406]: Unknown Initiator
    PTP Property 0xd303 [d303]: 1
    Battery Level [5001]: 100 (100, 0, 75, 0, 50, )

2019-10-15 23:14:34,034 - root - INFO - Using camera with preview functionality
2019-10-15 23:14:36,122 - root - INFO - _skip: "[4]"
2019-10-15 23:14:36,129 - root - INFO - Adding Logo : "False"
2019-10-15 23:14:36,129 - root - INFO - Using logo "/home/pi/Bilder/1024px-logo.png"
2019-10-15 23:14:36,129 - root - INFO - Using background "/home/pi/photobooth/supplementals/backgrounds/Fotopaper_background_forever_59.jpg"
2019-10-15 23:15:03,754 - root - INFO - Pic "0"
2019-10-15 23:15:03,833 - root - INFO - Pic "1"
2019-10-15 23:15:03,906 - root - INFO - Pic "2"
2019-10-15 23:15:04,077 - root - INFO - Saving picture as 2019-10-15/photobooth00037.jpg
2019-10-15 23:35:57,121 - root - INFO - Exiting photobooth with status code 0

```

**Additional context**

**Comment by websta911** [comment]
Hello, I looked into that and I have a hunch.
I looked into the new camera/gphoto2 module since there were some changes.
I am not exactly sure what is happening precisely but I copied over an old version and it ran with my eos 550 but not with eos m3. Whats the difference:
in the "old" implementation there are some settings which are beeing set when changing from active to Idle. If you do not have a config file with those settings the new module does not do it so you stay active all the time and I am not sure if that is the problem but I think it is. Because with the old version and the eos 550 the box could sit on "press the button" for some time and not freeze.

In the old module during idle the output is set to Off. that does not happen when you do not have a cfg file for your camera model under camera/models/

Your configuration looks fine so you can try copying the eos500d.cfg file already in the models folder and paste it as canoneos70d.cfg and try it out. If during startup or during running you are getting some error you can try deleting the problem cfg line or refine it using the cameraconfig in the photobooth log. 

For me I am not sure what to do because my output value is 'unknown value 0008' or 'Off' and that is all that is possible. I have to try to switch between those to but my time this up so I have to try again  another time. I hope there is some sense in that an it works for you if you create a canoneos70d.cfg file.Regards 
Christoph

**Comment by Tinker232** [comment]
Hey Christoph,
thanks for your reply. 
Meanwhile I tried the steps from your first post. Trying to control the camera via gphoto2 / python after the error occured also didnt enable the connection.
Copying the config-file and renaming it to canoneos70d.cfg was the solution! Now it works fine, also for a long time in idle without any errros. 
Thank you for your support Christoph...
Regards Tina
