### ISSUE TITLE
Can't install photobooth on Windows 10.

### ISSUE THREAD

**Issue by JohnMackYouTube05** [reuterbal/photobooth#203]
When I use Command Prompt and run the command `setup.py install`

This is what python throws back at me:
`C:\Users\liljm\Downloads\photobooth\photobooth>photobooth
Traceback (most recent call last):
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\Scripts\photobooth-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3126, in <module>
    @_call_aside
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycups' distribution was not found and is required by photobooth

C:\Users\liljm\Downloads\photobooth\photobooth>setup.py install
running install
running bdist_egg
running egg_info
writing photobooth.egg-info\PKG-INFO
writing dependency_links to photobooth.egg-info\dependency_links.txt
writing entry points to photobooth.egg-info\entry_points.txt
writing requirements to photobooth.egg-info\requires.txt
writing top-level names to photobooth.egg-info\top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'photobooth.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\photobooth
creating build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraDummy.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraGphoto2.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraGphoto2Cffi.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraGphoto2CommandLine.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraInterface.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraOpenCV.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\CameraPicamera.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\PictureDimensions.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\camera\__init__.py -> build\bdist.win32\egg\photobooth\camera
copying build\lib\photobooth\Config.py -> build\bdist.win32\egg\photobooth
copying build\lib\photobooth\defaults.cfg -> build\bdist.win32\egg\photobooth
creating build\bdist.win32\egg\photobooth\gpio
copying build\lib\photobooth\gpio\__init__.py -> build\bdist.win32\egg\photobooth\gpio
creating build\bdist.win32\egg\photobooth\gui
copying build\lib\photobooth\gui\GuiPostprocessor.py -> build\bdist.win32\egg\photobooth\gui
copying build\lib\photobooth\gui\GuiSkeleton.py -> build\bdist.win32\egg\photobooth\gui
creating build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\Frames.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\PyQt5Gui.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\Receiver.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\Widgets.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\Worker.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\Qt5Gui\__init__.py -> build\bdist.win32\egg\photobooth\gui\Qt5Gui
copying build\lib\photobooth\gui\__init__.py -> build\bdist.win32\egg\photobooth\gui
copying build\lib\photobooth\main.py -> build\bdist.win32\egg\photobooth
creating build\bdist.win32\egg\photobooth\printer
copying build\lib\photobooth\printer\PrinterPyCups.py -> build\bdist.win32\egg\photobooth\printer
copying build\lib\photobooth\printer\PrinterPyQt5.py -> build\bdist.win32\egg\photobooth\printer
copying build\lib\photobooth\printer\__init__.py -> build\bdist.win32\egg\photobooth\printer
copying build\lib\photobooth\StateMachine.py -> build\bdist.win32\egg\photobooth
copying build\lib\photobooth\Threading.py -> build\bdist.win32\egg\photobooth
copying build\lib\photobooth\util.py -> build\bdist.win32\egg\photobooth
creating build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\PictureList.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\PictureMailer.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\PictureSaver.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\PictureUploadWebdav.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\WorkerTask.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\worker\__init__.py -> build\bdist.win32\egg\photobooth\worker
copying build\lib\photobooth\__init__.py -> build\bdist.win32\egg\photobooth
copying build\lib\photobooth\__main__.py -> build\bdist.win32\egg\photobooth
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraDummy.py to CameraDummy.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraGphoto2.py to CameraGphoto2.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraGphoto2Cffi.py to CameraGphoto2Cffi.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraGphoto2CommandLine.py to CameraGphoto2CommandLine.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraInterface.py to CameraInterface.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraOpenCV.py to CameraOpenCV.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\CameraPicamera.py to CameraPicamera.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\PictureDimensions.py to PictureDimensions.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\camera\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\Config.py to Config.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gpio\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\GuiPostprocessor.py to GuiPostprocessor.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\GuiSkeleton.py to GuiSkeleton.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\Frames.py to Frames.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\PyQt5Gui.py to PyQt5Gui.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\Receiver.py to Receiver.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\Widgets.py to Widgets.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\Worker.py to Worker.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\Qt5Gui\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\gui\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\main.py to main.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\printer\PrinterPyCups.py to PrinterPyCups.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\printer\PrinterPyQt5.py to PrinterPyQt5.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\printer\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\StateMachine.py to StateMachine.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\Threading.py to Threading.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\util.py to util.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\PictureList.py to PictureList.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\PictureMailer.py to PictureMailer.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\PictureSaver.py to PictureSaver.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\PictureUploadWebdav.py to PictureUploadWebdav.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\WorkerTask.py to WorkerTask.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\worker\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\__init__.py to __init__.cpython-37.pyc
byte-compiling build\bdist.win32\egg\photobooth\__main__.py to __main__.cpython-37.pyc
installing package data to build\bdist.win32\egg
running install_data
creating build\bdist.win32\egg\usr
creating build\bdist.win32\egg\usr\share
creating build\bdist.win32\egg\usr\share\locale
creating build\bdist.win32\egg\usr\share\locale\de
creating build\bdist.win32\egg\usr\share\locale\de\LC_MESSAGES
copying C:\Users\liljm\Downloads\photobooth\photobooth\photobooth\locale\de\LC_MESSAGES\photobooth.mo -> build\bdist.win32\egg\usr\share\locale\de\LC_MESSAGES
creating build\bdist.win32\egg\usr\share\locale\en
creating build\bdist.win32\egg\usr\share\locale\en\LC_MESSAGES
copying C:\Users\liljm\Downloads\photobooth\photobooth\photobooth\locale\en\LC_MESSAGES\photobooth.mo -> build\bdist.win32\egg\usr\share\locale\en\LC_MESSAGES
creating build\bdist.win32\egg\usr\share\locale\es
creating build\bdist.win32\egg\usr\share\locale\es\LC_MESSAGES
copying C:\Users\liljm\Downloads\photobooth\photobooth\photobooth\locale\es\LC_MESSAGES\photobooth.mo -> build\bdist.win32\egg\usr\share\locale\es\LC_MESSAGES
creating build\bdist.win32\egg\usr\share\locale\fr
creating build\bdist.win32\egg\usr\share\locale\fr\LC_MESSAGES
copying C:\Users\liljm\Downloads\photobooth\photobooth\photobooth\locale\fr\LC_MESSAGES\photobooth.mo -> build\bdist.win32\egg\usr\share\locale\fr\LC_MESSAGES
creating build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\entry_points.txt -> build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying photobooth.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
photobooth.__pycache__.Config.cpython-37: module references __file__
photobooth.camera.__pycache__.CameraInterface.cpython-37: module references __file__
photobooth.gui.Qt5Gui.__pycache__.PyQt5Gui.cpython-37: module references __file__
creating 'dist\photobooth-0.5.dev3+g40f1cda-py3.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing photobooth-0.5.dev3+g40f1cda-py3.7.egg
removing 'c:\users\liljm\appdata\local\programs\python\python37-32\lib\site-packages\photobooth-0.5.dev3+g40f1cda-py3.7.egg' (and everything under it)
creating c:\users\liljm\appdata\local\programs\python\python37-32\lib\site-packages\photobooth-0.5.dev3+g40f1cda-py3.7.egg
Extracting photobooth-0.5.dev3+g40f1cda-py3.7.egg to c:\users\liljm\appdata\local\programs\python\python37-32\lib\site-packages
photobooth 0.5.dev3+g40f1cda is already the active version in easy-install.pth
Installing photobooth-script.py script to C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\Scripts
Installing photobooth.exe script to C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\Scripts
Installing photobooth.exe.manifest script to C:\Users\liljm\AppData\Local\Programs\Python\Python37-32\Scripts

Installed c:\users\liljm\appdata\local\programs\python\python37-32\lib\site-packages\photobooth-0.5.dev3+g40f1cda-py3.7.egg
Processing dependencies for photobooth==0.5.dev3+g40f1cda
Searching for pycups
Reading https://pypi.org/simple/pycups/
Downloading https://files.pythonhosted.org/packages/00/ce/836a0deb8b24bcd5f850f8fb97f99fb4abd7374e078b9e6df5a0838f8eb5/pycups-1.9.74.tar.bz2#sha256=86090f259a7c5d0d5caa3407a0e57c9e134027620cbc8f90bf4e37c8b53ed7b9
Best match: pycups 1.9.74
Processing pycups-1.9.74.tar.bz2
Writing C:\Users\liljm\AppData\Local\Temp\easy_install-fyppuuz4\pycups-1.9.74\setup.cfg
Running pycups-1.9.74\setup.py -q bdist_egg --dist-dir C:\Users\liljm\AppData\Local\Temp\easy_install-fyppuuz4\pycups-1.9.74\egg-dist-tmp-26hqsp2_
cupsmodule.c
cupsmodule.c(23): fatal error C1083: Cannot open include file: 'cups/cups.h': No such file or directory
error: Setup script exited with error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2`

Why can't I install this program? Please help.

### Specs: 
PC: HP Pavilion Gaming Laptop cx-0056wm
OS: Windows 10 Home Edition Build 1903
CPU: Intel Core i5 8th Gen
8GB DDR4 RAM
NVIDIA GTX1050Ti Graphics Chip
1TB HDD

**Comment by haviduck** [comment]
cups is unix only
