### ISSUE TITLE
Email Option and Gallery?

### ISSUE THREAD

**Issue by raspblu** [reuterbal/photobooth#75]
Is it possible for you to add in the features to email out the pictures that was just taken, and to display all pictures taken in a gallery?

**Comment by reuterbal** [comment]
The software is written such that it is relatively simple to add additional postprocessing tasks. 
Simply add another class derived from `WorkerTask` in [`photobooth/worker/__init__.py`](https://github.com/reuterbal/photobooth/blob/master/photobooth/worker/__init__.py), similarly to `PictureSaver`that implements the desired actions and enable them in `Worker` in the same file.

**Comment by MarioJanssen27** [comment]
Hello,

wie weit ist das standalone network mit der Gallerie?
Wo kann man helfen?

**Comment by oelegeirnaert** [comment]
Hi, currently working on a webserver to be able to make a gallery:
https://github.com/oelegeirnaert/photobooth/tree/webserver/photobooth

**Comment by reuterbal** [comment]
Hi @oelegeirnaert 
that looks very promising. Let me know if you need to know anything in order to integrate it!

**Comment by MarioJanssen27** [comment]
Is it possible to run a standalone network with a gallery with the project?

**Comment by MarioJanssen27** [comment]
Can a standalone network with a gallery be operated with the project?

---------------------------------------------------------------
in deutsch

Kann man mit dem Projekt auch ein Standalone Netzwerk mit einer Gallerie betreiben?

**Comment by hotdogreen** [comment]
Well ... I’m not very pro with these things. 
Do i need to install the software again or can I just copy paste your additional files to make the gallery happen?! 
(Sorry)

**Comment by oelegeirnaert** [comment]
I just did some changes in my code.

**Comment by MarioJanssen27** [comment]
I cannot start the Phothbooth from (https://github.com/oelegeirnaert/photobooth). What am I doing wrong?

I get the following error message:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/photobooth/photobooth/__init__.py", line 21, in <module>
    from .main import main
  File "/home/pi/photobooth/photobooth/main.py", line 40, in <module>
    from .webserver import Webserver
  File "/home/pi/photobooth/photobooth/webserver/__init__.py", line 4, in <module>
    from simple_http_server import request_map
ImportError: No module named 'simple_http_server'

**Comment by wikijm** [comment]
Hi @MarioJanssen27 

It might be better to create an issue on @oelegeirnaert, because your issue is specific to it.

**Comment by oelegeirnaert** [comment]
Indeed, you should create issues on my fork, if everything is finnished, we can merge again :-)
But to answer your questions, you need to install the http_server via PIP.

**pip install simple_http_server**
Another thing... I've changed the startup params so that the gui wasn't showing all the time while developing. So you beter start it like this:

**python -m photobooth --debug -w --gui**
I should change this that the GUI is popping up by default.

Enjoy!

Kr,
Oele Geirnaert

**Comment by serpentes80** [comment]
@oelegeirnaert
not so easy to create an issue on your fork ;-)
there's no "issue" tab :-P

btw: tested the latest version yesterday and the website doesn't show anything. Neither pictures nor qr code or anything

**Comment by hotdogreen** [comment]
Not able to get it running, either 👀

**Comment by oelegeirnaert** [comment]
Just enabled it!
